[package]
name = "fast-ccip-bot-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = { version = "0.11" }
ethers = "2.0.4"
ethers-contract = "2.0.4"
serde = "1.0.163"
futures = "0.3.28"
hex = "0.4.3"
num-bigint = "0.4.4"
